-- Schema for the YouTube Trends Platform (Cycling & Triathlon).
-- See CLAUDE.md "Data model" for the full rationale behind this design.
--
-- Tables are created in dependency order: channels -> videos -> video_snapshots.
-- A foreign key can only reference a table that already exists, so channels
-- (referenced by videos) must be created before videos, and videos
-- (referenced by video_snapshots) before video_snapshots. job_runs has no
-- foreign keys and can be created at any point.

-- ============================================================
-- channels — 40 rows, changes almost never
-- ============================================================
CREATE TABLE channels (
    channel_id text PRIMARY KEY,
    name text NOT NULL,
    -- Channel rows are inserted by hand; a typo here (e.g. 'brand' instead
    -- of 'brands') would silently exclude that channel from every category
    -- query rather than raising an error.
    category text NOT NULL CHECK (category IN ('brands', 'triathletes', 'teams', 'influencers')),
    -- Nullable: fetched from the API on collection runs, not entered by hand.
    avatar_url text,
    added_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- videos — one row per video, immutable facts
-- ============================================================
CREATE TABLE videos (
    video_id text PRIMARY KEY,
    channel_id text NOT NULL REFERENCES channels (channel_id),
    published_at timestamptz NOT NULL,
    duration_seconds integer NOT NULL,
    is_short boolean NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT now()
);

-- Every category query joins channels -> videos through channel_id.
-- Postgres does not index foreign key columns automatically, so this
-- must be created explicitly.
CREATE INDEX idx_videos_channel_id ON videos (channel_id);

-- ============================================================
-- video_snapshots — one row per video per run, the time series
-- ============================================================
CREATE TABLE video_snapshots (
    video_id text NOT NULL REFERENCES videos (video_id),
    snapshot_date date NOT NULL,
    views bigint NOT NULL,
    -- likes/comments are nullable: the YouTube API omits likeCount when a
    -- creator hides likes, and commentCount when comments are disabled.
    -- Those values are genuinely absent, not zero — writing 0 would
    -- misrepresent a disabled feature as an absence of engagement and
    -- would distort engagement rate.
    likes integer,
    comments integer,
    title text NOT NULL,
    thumbnail_url text NOT NULL,
    PRIMARY KEY (video_id, snapshot_date)
);

-- The weekly job filters on snapshot_date every run.
CREATE INDEX idx_video_snapshots_snapshot_date ON video_snapshots (snapshot_date);

-- ============================================================
-- job_runs — one row per execution, operational log
-- Deliberately has no foreign keys to the other three tables: it is a
-- record of process execution, not part of the analytical model.
-- ============================================================
CREATE TABLE job_runs (
    -- Identity, not bigserial: bigserial creates a separate sequence object
    -- with its own privileges, which service_role would need granted
    -- separately (auto-expose is off). An identity column's sequence is
    -- owned by the table, so the table's INSERT grant covers it too.
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    status text NOT NULL CHECK (status IN ('running', 'success', 'failed')),
    mode text NOT NULL CHECK (mode IN ('daily', 'weekly', 'backfill')),
    channels_processed integer,
    snapshots_written integer,
    error_message text
);

-- ============================================================
-- Row Level Security
--
-- This project was created with "Automatically expose new tables" turned
-- OFF, so Supabase's auto-generated REST API starts with zero access to
-- these tables regardless of RLS. We still enable RLS on all four tables
-- and create no policies, as a second, independent layer: even if grants
-- are ever loosened (e.g. a SELECT grant added for anon later), a table
-- with RLS on and no policies serves zero rows to that role by default.
-- The service_role key used by the collection job bypasses RLS entirely,
-- so this has no effect on the job itself.
-- ============================================================
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_runs ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- Grants
--
-- With auto-expose off, no role has any privileges on these tables until
-- granted explicitly. service_role is the role the collection job
-- authenticates as (via the Supabase secret key), so it needs to read
-- existing rows (to avoid re-inserting videos) and write new ones.
-- No DELETE is granted: nothing in the job removes rows. -- Nothing is granted to authenticated. Public read access for anon was a
-- deliberate later step rather than a default, taken 2026-08-21 — see the
-- block below.
-- ============================================================
GRANT SELECT, INSERT, UPDATE ON channels TO service_role;
GRANT SELECT, INSERT, UPDATE ON videos TO service_role;
GRANT SELECT, INSERT, UPDATE ON video_snapshots TO service_role;
GRANT SELECT, INSERT, UPDATE ON job_runs TO service_role;
-- ================================================================
-- Front-end access — anon, SELECT only.
--
-- Added 2026-08-21, when the scoring view was built. Until then no role but
-- service_role held any privilege on anything here.
--
-- SELECT only. No INSERT, UPDATE or DELETE to anon under any circumstances:
-- the collection job remains the only writer.
--
-- job_runs is deliberately absent. Neither the live scoring query nor the
-- materialised view built from it ever reads job_runs, and it holds our own
-- operational data rather than public YouTube data. Verified: as anon,
-- `select count(*) from job_runs` returns 42501 permission denied.
--
-- Historical note, since the reasoning changed under this grant without the
-- grant itself changing: `scoring_view` was originally a security_invoker
-- LIVE view, so anon's direct SELECT on videos/channels/video_snapshots
-- below existed because the view checked anon's OWN permissions on those
-- tables at query time — granting on the view alone would have returned
-- empty results with no error, the RLS failure mode, and the hardest kind
-- to debug. `scoring_view` is now a MATERIALISED view (see sql/scoring_view.sql)
-- refreshed by service_role, which is a definer-style read of the base
-- tables regardless of who queries the stored result afterwards — so anon's
-- grant on `scoring_view` itself no longer depends on these three. They stay
-- granted regardless: `channels` is still read directly by the front end
-- (see queries.js getChannels()), and revoking the other two wasn't asked
-- for and isn't done here on a guess.
-- ================================================================

grant select on videos          to anon;
grant select on channels        to anon;
grant select on video_snapshots to anon;
grant select on scoring_view    to anon;

-- RLS applies to tables, not views, so there is no policy for scoring_view —
-- its grant plus these three policies are what govern it. `using (true)`
-- is the row filter: true for every row, so all of them. The grant above is
-- what keeps that meaning read and nothing more.
create policy "anon reads videos"
  on videos for select to anon using (true);

create policy "anon reads channels"
  on channels for select to anon using (true);

create policy "anon reads video_snapshots"
  on video_snapshots for select to anon using (true);

-- ============================================================
-- Views
-- ============================================================

-- Convenience view for reading `videos` with the channel name attached, rather
-- than the opaque UC... id. Nothing is stored: the name lives once on
-- `channels` and is joined at read time, so a channel rename is a single-cell
-- change rather than an update across every video row.
--
-- security_invoker = true is load-bearing. A Postgres view defaults to running
-- as its owner, so a view owned by postgres reads through RLS as postgres —
-- which would let a SELECT grant to anon bypass the seal on the underlying
-- tables entirely. With security_invoker the view checks the querying role's
-- own permissions, so the two access layers documented above still hold.
--
-- No grants to anon or authenticated. Like the tables, this opens only when the
-- front end needs it, and only for SELECT.
create or replace view videos_readable
with (security_invoker = true) as
select
  v.video_id,
  c.name as channel_name,
  c.category,
  v.published_at,
  v.duration_seconds,
  v.is_short,
  v.first_seen_at
from videos v
join channels c on c.channel_id = v.channel_id;

revoke all on videos_readable from anon, authenticated;

-- ============================================================
-- scoring_view — structural mirror only. The full query (the CTEs, the
-- LATERAL baseline computation, every comment explaining why) lives in
-- exactly one place, sql/scoring_view.sql, and is deliberately not
-- duplicated here — same single-source principle as DEFAULT_FILTERS and
-- getPageSize in frontend/src/lib/filters.js. Run that file, not this
-- section, to actually create or change any of this. What follows is a
-- description of what exists, kept here because this file is meant to be
-- a complete account of the database, not the objects themselves.
--
-- Two objects. scoring_view_live is the query — a security_invoker = true
-- live view, ungranted, read by nothing except the refresh below.
-- scoring_view is a materialised view, `select * from scoring_view_live`,
-- carrying three indexes (a unique index on (video_id, "window", metric),
-- and one each on value and outlier_score, both ending nulls last to match
-- the front end's required ordering) and the only grant: SELECT to anon.
--
-- Materialised rather than live as of 2026-08-23, reversing the 2026-08-19
-- decision to keep this live. Measured cause: four categories merged on the
-- long-form arm exceeds anon's 3-second statement_timeout even fetching
-- rows alone, with no count involved — the view had already been optimised
-- 730x and had nothing further to give, and a live view has no storage of
-- its own to index. The silent-staleness risk a materialised view normally
-- carries is closed in collect.py instead: refresh_scoring_view() is
-- called only after the three failure checks pass, and a failed refresh is
-- written to job_runs as status = 'failed' with an error_message naming
-- the refresh, which suppresses the Healthchecks ping — the same loud
-- failure path as everything else the job does.
--
-- refresh_scoring_view() is SECURITY DEFINER, owned by postgres, because
-- REFRESH requires ownership of the view and service_role does not own it.
-- EXECUTE is granted to service_role only — never to anon or PUBLIC — so
-- this is the one place in the schema where a role reaches an elevated
-- privilege through a function rather than holding it directly, and it is
-- reachable by exactly the one role authorised to trigger a refresh.
--
-- Genuine exception to the two-layer access model, stated here as well as
-- in scoring_view.sql: RLS does not apply to materialised views, and a
-- materialised view cannot be security_invoker — it always reads the
-- tables it's built from as its owner. Accepted because it exposes nothing
-- anon could not already reach directly (see the historical note on the
-- anon grants above), not because the exception is free.
-- ============================================================