-- Schema for the YouTube Trends Platform (Cycling & Triathlon).
-- See CLAUDE.md "Data model" for the full rationale behind this design.
--
-- Tables are created in dependency order: channels -> videos -> video_snapshots.
-- A foreign key can only reference a table that already exists, so channels
-- (referenced by videos) must be created before videos, and videos
-- (referenced by video_snapshots) before video_snapshots. job_runs has no
-- foreign keys and can be created at any point.

-- ============================================================
-- channels — 40 rows, changes almost never
-- ============================================================
CREATE TABLE channels (
    channel_id text PRIMARY KEY,
    name text NOT NULL,
    -- Channel rows are inserted by hand; a typo here (e.g. 'brand' instead
    -- of 'brands') would silently exclude that channel from every category
    -- query rather than raising an error.
    category text NOT NULL CHECK (category IN ('brands', 'triathletes', 'teams', 'influencers')),
    added_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- videos — one row per video, immutable facts
-- ============================================================
CREATE TABLE videos (
    video_id text PRIMARY KEY,
    channel_id text NOT NULL REFERENCES channels (channel_id),
    published_at timestamptz NOT NULL,
    duration_seconds integer NOT NULL,
    is_short boolean NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT now()
);

-- Every category query joins channels -> videos through channel_id.
-- Postgres does not index foreign key columns automatically, so this
-- must be created explicitly.
CREATE INDEX idx_videos_channel_id ON videos (channel_id);

-- ============================================================
-- video_snapshots — one row per video per run, the time series
-- ============================================================
CREATE TABLE video_snapshots (
    video_id text NOT NULL REFERENCES videos (video_id),
    snapshot_date date NOT NULL,
    views bigint NOT NULL,
    -- likes/comments are nullable: the YouTube API omits likeCount when a
    -- creator hides likes, and commentCount when comments are disabled.
    -- Those values are genuinely absent, not zero — writing 0 would
    -- misrepresent a disabled feature as an absence of engagement and
    -- would distort engagement rate.
    likes integer,
    comments integer,
    title text NOT NULL,
    thumbnail_url text NOT NULL,
    PRIMARY KEY (video_id, snapshot_date)
);

-- The weekly job filters on snapshot_date every run.
CREATE INDEX idx_video_snapshots_snapshot_date ON video_snapshots (snapshot_date);

-- ============================================================
-- job_runs — one row per execution, operational log
-- Deliberately has no foreign keys to the other three tables: it is a
-- record of process execution, not part of the analytical model.
-- ============================================================
CREATE TABLE job_runs (
    -- Identity, not bigserial: bigserial creates a separate sequence object
    -- with its own privileges, which service_role would need granted
    -- separately (auto-expose is off). An identity column's sequence is
    -- owned by the table, so the table's INSERT grant covers it too.
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    status text NOT NULL CHECK (status IN ('running', 'success', 'failed')),
    channels_processed integer,
    snapshots_written integer,
    error_message text
);

-- ============================================================
-- Row Level Security
--
-- This project was created with "Automatically expose new tables" turned
-- OFF, so Supabase's auto-generated REST API starts with zero access to
-- these tables regardless of RLS. We still enable RLS on all four tables
-- and create no policies, as a second, independent layer: even if grants
-- are ever loosened (e.g. a SELECT grant added for anon later), a table
-- with RLS on and no policies serves zero rows to that role by default.
-- The service_role key used by the collection job bypasses RLS entirely,
-- so this has no effect on the job itself.
-- ============================================================
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_runs ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- Grants
--
-- With auto-expose off, no role has any privileges on these tables until
-- granted explicitly. service_role is the role the collection job
-- authenticates as (via the Supabase secret key), so it needs to read
-- existing rows (to avoid re-inserting videos) and write new ones.
-- No DELETE is granted: nothing in the job removes rows. Nothing is
-- granted to anon or authenticated — public read access for the front
-- end is a deliberate later step, not a default.
-- ============================================================
GRANT SELECT, INSERT, UPDATE ON channels TO service_role;
GRANT SELECT, INSERT, UPDATE ON videos TO service_role;
GRANT SELECT, INSERT, UPDATE ON video_snapshots TO service_role;
GRANT SELECT, INSERT, UPDATE ON job_runs TO service_role;
