-- Schema for the YouTube Trends Platform (Cycling & Triathlon).
-- See CLAUDE.md "Data model" for the full rationale behind this design.
--
-- Tables are created in dependency order: channels -> videos -> video_snapshots.
-- A foreign key can only reference a table that already exists, so channels
-- (referenced by videos) must be created before videos, and videos
-- (referenced by video_snapshots) before video_snapshots. job_runs has no
-- foreign keys and can be created at any point.

-- ============================================================
-- channels — 40 rows, changes almost never
-- ============================================================
CREATE TABLE channels (
    channel_id text PRIMARY KEY,
    name text NOT NULL,
    -- Channel rows are inserted by hand; a typo here (e.g. 'brand' instead
    -- of 'brands') would silently exclude that channel from every category
    -- query rather than raising an error.
    category text NOT NULL CHECK (category IN ('brands', 'triathletes', 'teams', 'influencers')),
    -- Nullable: fetched from the API on collection runs, not entered by hand.
    avatar_url text,
    added_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- videos — one row per video, immutable facts
-- ============================================================
CREATE TABLE videos (
    video_id text PRIMARY KEY,
    channel_id text NOT NULL REFERENCES channels (channel_id),
    published_at timestamptz NOT NULL,
    duration_seconds integer NOT NULL,
    is_short boolean NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT now()
);

-- Every category query joins channels -> videos through channel_id.
-- Postgres does not index foreign key columns automatically, so this
-- must be created explicitly.
CREATE INDEX idx_videos_channel_id ON videos (channel_id);

-- ============================================================
-- video_snapshots — one row per video per run, the time series
-- ============================================================
CREATE TABLE video_snapshots (
    video_id text NOT NULL REFERENCES videos (video_id),
    snapshot_date date NOT NULL,
    views bigint NOT NULL,
    -- likes/comments are nullable: the YouTube API omits likeCount when a
    -- creator hides likes, and commentCount when comments are disabled.
    -- Those values are genuinely absent, not zero — writing 0 would
    -- misrepresent a disabled feature as an absence of engagement and
    -- would distort engagement rate.
    likes integer,
    comments integer,
    title text NOT NULL,
    thumbnail_url text NOT NULL,
    PRIMARY KEY (video_id, snapshot_date)
);

-- The weekly job filters on snapshot_date every run.
CREATE INDEX idx_video_snapshots_snapshot_date ON video_snapshots (snapshot_date);

-- ============================================================
-- job_runs — one row per execution, operational log
-- Deliberately has no foreign keys to the other three tables: it is a
-- record of process execution, not part of the analytical model.
-- ============================================================
CREATE TABLE job_runs (
    -- Identity, not bigserial: bigserial creates a separate sequence object
    -- with its own privileges, which service_role would need granted
    -- separately (auto-expose is off). An identity column's sequence is
    -- owned by the table, so the table's INSERT grant covers it too.
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    status text NOT NULL CHECK (status IN ('running', 'success', 'failed')),
    mode text NOT NULL CHECK (mode IN ('daily', 'weekly', 'backfill')),
    channels_processed integer,
    snapshots_written integer,
    error_message text
);

-- ============================================================
-- Row Level Security
--
-- This project was created with "Automatically expose new tables" turned
-- OFF, so Supabase's auto-generated REST API starts with zero access to
-- these tables regardless of RLS. We still enable RLS on all four tables
-- and create no policies, as a second, independent layer: even if grants
-- are ever loosened (e.g. a SELECT grant added for anon later), a table
-- with RLS on and no policies serves zero rows to that role by default.
-- The service_role key used by the collection job bypasses RLS entirely,
-- so this has no effect on the job itself.
-- ============================================================
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_runs ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- Grants
--
-- With auto-expose off, no role has any privileges on these tables until
-- granted explicitly. service_role is the role the collection job
-- authenticates as (via the Supabase secret key), so it needs to read
-- existing rows (to avoid re-inserting videos) and write new ones.
-- No DELETE is granted: nothing in the job removes rows. -- Nothing is granted to authenticated. Public read access for anon was a
-- deliberate later step rather than a default, taken 2026-08-21 — see the
-- block below.
-- ============================================================
GRANT SELECT, INSERT, UPDATE ON channels TO service_role;
GRANT SELECT, INSERT, UPDATE ON videos TO service_role;
GRANT SELECT, INSERT, UPDATE ON video_snapshots TO service_role;
GRANT SELECT, INSERT, UPDATE ON job_runs TO service_role;
-- ================================================================
-- Front-end access — anon, SELECT only.
--
-- Added 2026-08-21, when the scoring view was built. Until then no role but
-- service_role held any privilege on anything here.
--
-- scoring_view is security_invoker = true, so it checks the QUERYING role's
-- permissions on the underlying tables rather than its creator's. anon
-- therefore needs both layers opened on the three tables the view reads, not
-- only on the view itself. Granting on the view alone returns empty results
-- with no error — the RLS failure mode, and the hardest kind to debug.
--
-- The alternative was to make scoring_view a definer view so it could read
-- the tables on anon's behalf while the tables stayed sealed. Rejected — see
-- DECISIONS.md 2026-08-21.
--
-- SELECT only. No INSERT, UPDATE or DELETE to anon under any circumstances:
-- the collection job remains the only writer.
--
-- job_runs is deliberately absent. The view never reads it, and it holds our
-- own operational data rather than public YouTube data. Verified: as anon,
-- `select count(*) from job_runs` returns 42501 permission denied.
-- ================================================================

grant select on videos          to anon;
grant select on channels        to anon;
grant select on video_snapshots to anon;
grant select on scoring_view    to anon;

-- RLS applies to tables, not views, so there is no policy for scoring_view —
-- its grant plus these three policies are what govern it. `using (true)`
-- is the row filter: true for every row, so all of them. The grant above is
-- what keeps that meaning read and nothing more.
create policy "anon reads videos"
  on videos for select to anon using (true);

create policy "anon reads channels"
  on channels for select to anon using (true);

create policy "anon reads video_snapshots"
  on video_snapshots for select to anon using (true);

-- ============================================================
-- Views
-- ============================================================

-- Convenience view for reading `videos` with the channel name attached, rather
-- than the opaque UC... id. Nothing is stored: the name lives once on
-- `channels` and is joined at read time, so a channel rename is a single-cell
-- change rather than an update across every video row.
--
-- security_invoker = true is load-bearing. A Postgres view defaults to running
-- as its owner, so a view owned by postgres reads through RLS as postgres —
-- which would let a SELECT grant to anon bypass the seal on the underlying
-- tables entirely. With security_invoker the view checks the querying role's
-- own permissions, so the two access layers documented above still hold.
--
-- No grants to anon or authenticated. Like the tables, this opens only when the
-- front end needs it, and only for SELECT.
create or replace view videos_readable
with (security_invoker = true) as
select
  v.video_id,
  c.name as channel_name,
  c.category,
  v.published_at,
  v.duration_seconds,
  v.is_short,
  v.first_seen_at
from videos v
join channels c on c.channel_id = v.channel_id;

revoke all on videos_readable from anon, authenticated;